### ISSUE TITLE
titles of chapter

### ISSUE THREAD

**Issue by mpbrenner** [probml/pyprobml#100]
In the new format, you are listing each of the chapters by its number. It would be really helpful to specify the topic as well. This way a person could find what they are looking for without having to have the book in front of them.

**Comment by mjsML** [comment]
Hi @mpbrenner 
IIUC you are suggesting e.g. for chapter 1:
- rename `/book1/chapters/chap1.md` to `/book1/chapters/chapter1_Introduction.md` 
- rename `/book1/figures/chapter1_figures.ipynb` to `/book1/figures/chapter1_Introduction_figures.ipynb`

Is this correct?

**Comment by murphyk** [comment]
Michael, you can always use https://github.com/probml/pyprobml/blob/master/book1/README.md as the "rosetta stone" to convert chapter numbers to names, without needing access to the book. Is that sufficient or do you think we should do what Mahmoud is suggesting, and make long filenames? (This is now all automatically generated, which is why we switched to using numbers, but we can add names too.)

**Comment by murphyk** [comment]
@animesh-007 The current priority is to translate legacy matlab code (see https://github.com/probml/pyprobml/issues/99). The deep learning code can come later.

@mpbrenner I will leave filenames as chapter1.md for now, without including the name of the chapter, ok?

**Comment by mpbrenner** [comment]
Kevin: Sorry for teh slow reply.

The reason I made this suggestion is that I'm using your book and also this
repo in my class at Harvard this semester (Applied Math 216 on Inverse
Problems). The issue is that because of the structure of the class we are
skipping around the book, and also this repo.  ie suppose I want to find
the material you have on logistic regression, or on some type of neural
network. It is easier if it is labeled as such in the repo. Otherwise we
need to translate from the table of contents.

Having said this, I don't think it is a huge problem -- I just noticed it
and opened this issue as I was always opening the repo looking for your
notebook and code on topic XXX, and then it defaulted to chapter numbers. I
don't know if others will use the book (and the repo) in the same way and
so this might just be my peculiar problem.

Having said all of this--I should take this opportunity to say that this is
an *extremely* useful resource.....the way this is constructed is really
great.

michael

On Fri, Mar 12, 2021 at 6:04 PM Kevin P Murphy ***@***.***>
wrote:

> @animesh-007
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_animesh-2D007&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=218Y_AEyh-xV1DmGk8Lg-wWwnzIJIQyVbODTpWISUJc&m=H6AJ3tzZ8d5FsyQKx0XME9msWgh9PRkNancKKT4C_JU&s=xO5GZQEYsFSL_thCTfUw7bHeuqVhHWQ-k2de5JgVqIQ&e=>
> The current priority is to translate legacy matlab code (see #99
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_probml_pyprobml_issues_99&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=218Y_AEyh-xV1DmGk8Lg-wWwnzIJIQyVbODTpWISUJc&m=H6AJ3tzZ8d5FsyQKx0XME9msWgh9PRkNancKKT4C_JU&s=rV-ZKOPJMc2hP3h5ChU1BGQLq12xvJJso4uZ9SUV-XQ&e=>).
> The deep learning code can come later.
>
> @mpbrenner
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mpbrenner&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=218Y_AEyh-xV1DmGk8Lg-wWwnzIJIQyVbODTpWISUJc&m=H6AJ3tzZ8d5FsyQKx0XME9msWgh9PRkNancKKT4C_JU&s=9H2OGOCNOpaefdhBIGIYN_hm6lXLYjPqUbMdtRs0KuA&e=>
> I will leave filenames as chapter1.md for now, without including the name
> of the chapter, ok?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_probml_pyprobml_issues_100-23issuecomment-2D797804463&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=218Y_AEyh-xV1DmGk8Lg-wWwnzIJIQyVbODTpWISUJc&m=H6AJ3tzZ8d5FsyQKx0XME9msWgh9PRkNancKKT4C_JU&s=Lzjp7J1sq6sx1mSeV8bw3CQaG8CMW7tb8yjRRL9UWYE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGDKATS6YKKWBGWHZ2ZGIZ3TDKFVNANCNFSM4Y3URKNA&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=218Y_AEyh-xV1DmGk8Lg-wWwnzIJIQyVbODTpWISUJc&m=H6AJ3tzZ8d5FsyQKx0XME9msWgh9PRkNancKKT4C_JU&s=EsP8_cwQNpnl8S5jddhcXaGE8ftlmvAv0Lk-6RKFyaU&e=>
> .
>


-- 
Michael P. Brenner
School of Engineering and Applied Sciences
Harvard University
29 Oxford St
Cambridge, MA 02138
617 495 3336
FAX 617 496 0601
www.seas.harvard.edu/brenner

**Comment by murphyk** [comment]
Michael, glad to hear the book is useful in your class. Please have the students file issues as well :)
@mjsML: can you please rerun your script and append chapter names to  in all the auto-generated figures/chapter_figures.ipynb files? Can you also rename all  the existing manually created chapters/chapX.md files using the same script?

**Comment by mjsML** [comment]
> Hi @mpbrenner
> IIUC you are suggesting e.g. for chapter 1:
> 
> * rename `/book1/chapters/chap1.md` to `/book1/chapters/chapter1_Introduction.md`
> * rename `/book1/figures/chapter1_figures.ipynb` to `/book1/figures/chapter1_Introduction_figures.ipynb`
> 
> Is this correct?

@murphyk just to confirm, so the above right?

**Comment by murphyk** [comment]
@mjsML  Yes, chapter1_Introduction_figures.ipynb.

**Comment by mjsML** [comment]
@mpbrenner Apologies for the delay in fixing this. It has been a busy few weeks. I just pushed the changes you requested. Let me know if this works.
