### ISSUE TITLE
Add demo for ekf vs ukf

### ISSUE THREAD

**Issue by petergchang** [probml/pyprobml#1017]
Add a Jupyter notebook that demonstrates ukf's capacity to better approximate global distribution of non-linear transformation, akin to Sarkka's Figures 5.3, 5.4, 5.5, as shown below
<img width="508" alt="Screen Shot 2022-07-19 at 6 08 55 PM" src="https://user-images.githubusercontent.com/16075389/179856933-906cc504-dcfc-45b6-954b-24f1ba7f5cf0.png">
<img width="500" alt="Screen Shot 2022-07-19 at 6 09 01 PM" src="https://user-images.githubusercontent.com/16075389/179856935-ad198a60-ccdc-44c9-9553-ae9de8f40209.png">
.

**Comment by murphyk** [comment]
done!
