### ISSUE TITLE
make tikz for hbnn fig 

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#1034]
<img width="699" alt="Screen Shot 2022-07-20 at 11 01 06 PM" src="https://user-images.githubusercontent.com/4632336/180140519-3b8e2f71-2491-4ec6-acd3-03a06302a8d7.png">

**Comment by karm-patel** [comment]
Currently, I'm working on this.

**Comment by karm-patel** [comment]
Added
![image](https://user-images.githubusercontent.com/59387624/180359163-26fb00d9-5f4a-4e52-9c59-2642d4adb768.png)
