### ISSUE TITLE
add new  GP plots 

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#1035]
<img width="719" alt="Screen Shot 2022-07-20 at 11 05 46 PM" src="https://user-images.githubusercontent.com/4632336/180141159-0c838b78-68a4-4e0f-b088-5c65d10dfdde.png">

**Comment by murphyk** [comment]
<img width="719" alt="Screen Shot 2022-07-20 at 11 06 42 PM" src="https://user-images.githubusercontent.com/4632336/180141270-1d955d82-055d-49f5-a6cd-a6474896391a.png">

**Comment by patel-zeel** [comment]
@murphyk Added to bookv2
