### ISSUE TITLE
MIT press issue #7: Line weight is too thin

### ISSUE THREAD

**Issue by karm-patel** [probml/pyprobml#1059]
-  [x] 4.33: p166
 - [x] 5.12a
 - [x] 6.3a
 - [x] 8.10
 - [ ] 9.11
 - [x] 10.15
 - [ ] 10.17a
 - [ ] 11.6
 - [x] 12.5 https://github.com/probml/pyprobml/blob/master/notebooks/book2/12/gibbs_gauss_demo.ipynb
 - [ ] 12.7
 - [ ] 12.22
 - [ ] 18.19a - #1062 
 - [ ] 18.28
 - [x] 28.18: https://github.com/probml/pyprobml/blob/master/notebooks/book1/20/binary_fa_demo.ipynb
 - [ ] 30.3
 - [ ] 30.5b = #1063
 - [ ] 31.7
 - [x] 31.8b = #1061 
 - [x] 34.11 - #1064
 - [ ] 35.4

**Comment by karm-patel** [comment]
tikzfy: 31.8 (b)
![image](https://user-images.githubusercontent.com/59387624/180637291-8df10c1d-2f80-42b6-843c-84942d019466.png)

**Comment by karm-patel** [comment]
tikzfy: Fig 18.19
![image](https://user-images.githubusercontent.com/59387624/180637357-4d41e086-e476-4c6a-b1ca-aa1de2b7e64a.png)

**Comment by patel-zeel** [comment]
Carry forward in #1071
