### ISSUE TITLE
convert FFG figs to tikz figs 4.46, 4.47

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#1070]
<img width="443" alt="Screen Shot 2022-07-25 at 9 06 19 AM" src="https://user-images.githubusercontent.com/4632336/180824244-45471c9a-b16d-4f54-9966-40c77add13d7.png">

**Comment by willtryagain** [comment]
Can I create these figures?
I am not very familiar with TikZ, but I can learn quickly because of being comfortable with LaTeX.

**Comment by murphyk** [comment]
Actually those figures don't look too bad. If you have cycles and want to learn tikz, I would request you recreate the figures below instead.
<img width="710" alt="Screenshot 2023-01-20 at 4 14 50 PM" src="https://user-images.githubusercontent.com/4632336/213828143-d6c92f5a-bd87-44ec-a66b-09219761a8ef.png">
<img width="684" alt="Screenshot 2023-01-20 at 4 15 28 PM" src="https://user-images.githubusercontent.com/4632336/213828151-47ab398b-3fbb-4dd6-ba0e-e1a468b2d7ec.png">

**Comment by willtryagain** [comment]
Are these figures for $4.54$ ok? [Here](https://www.overleaf.com/read/wbdjzvmtcnqm) is the link for the code 
![image](https://user-images.githubusercontent.com/41161981/213858902-9fade2c8-aeb6-4a89-858c-633fac5bda72.png)

![image](https://user-images.githubusercontent.com/41161981/213858884-57bba978-bdd7-45ff-9306-1399cec9563c.png)

**Comment by murphyk** [comment]
Thanks, this looks great!

**Comment by murphyk** [comment]
If you have time, after you convert 4.42, can you please also convert the attached ones? (They are currently generated in python, but tikz will give higher quality, and will be easier for me to edit.) Thanks! (I will add your name to the acknowledgements :)

<img width="686" alt="Screenshot 2023-01-21 at 8 40 28 AM" src="https://user-images.githubusercontent.com/4632336/213877295-84be6512-5f6c-4326-8cfe-7e92b1768ff4.png">

<img width="701" alt="Screenshot 2023-01-21 at 8 41 07 AM" src="https://user-images.githubusercontent.com/4632336/213877297-61730d8b-3545-4837-b179-c221d7ee0f25.png">
<img width="692" alt="Screenshot 2023-01-21 at 8 45 51 AM" src="https://user-images.githubusercontent.com/4632336/213877504-e9634527-5ee9-4e6c-af9a-57c31194309a.png">

<img width="698" alt="Screenshot 2023-01-21 at 8 45 57 AM" src="https://user-images.githubusercontent.com/4632336/213877505-49429d3c-8381-4f44-8128-577a143d17fc.png">

**Comment by willtryagain** [comment]
Hi, I have created the figures. You can view them on the link I shared previously.

**Comment by murphyk** [comment]
great, thanks!
