### ISSUE TITLE
latexify adf_logistic_regression_demo.ipynb

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#1091]
I tried adding latexify to 
https://github.com/probml/pyprobml/blob/master/notebooks/book2/15/adf_logistic_regression_demo.ipynb
but it looks ugly. And without it looks bad too

<img width="627" alt="Screen Shot 2022-07-28 at 2 54 17 PM" src="https://user-images.githubusercontent.com/4632336/181644329-05db76f0-32be-4c5d-bd7f-df677aa73052.png">

**Comment by karm-patel** [comment]
Done
