### ISSUE TITLE
tweak book 1 fog 7.6  gaussEvec.ipynb

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#1094]
To solve https://github.com/probml/pml-book/issues/440
Tweak
https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/book1/07/gaussEvec.ipynb
The exponents should be lambda^{-1/2}. I tried changing the text but the figure no longer renders properly (u_1, u_2 axis broken)

<img width="479" alt="Screen Shot 2022-07-28 at 11 55 07 PM" src="https://user-images.githubusercontent.com/4632336/181701063-8cf36364-ae6c-41bd-8289-4bad7594bc14.png">

**Comment by Mrutyunjay01** [comment]
![image](https://user-images.githubusercontent.com/53314831/211854710-b5908b14-31d5-4059-ae91-667a56a23fb3.png)

Is this the desired orientation?

Colab notebook link: [here](https://colab.research.google.com/drive/1hFfK-9qWep8cgZ1s03d9nmKqRc82oyHl?usp=sharing)

**Comment by murphyk** [comment]
Solved in https://github.com/probml/pyprobml/blob/master/notebooks/book1/07/gaussEvec.ipynb
