### ISSUE TITLE
colab_intro.ipynb "Notebook not found"

### ISSUE THREAD

**Issue by nickdgardner** [probml/pyprobml#1107]
[Opening this issue because it seems colab_intro.ipynb is supposed to exist but does not yet--sorry if I am just missing something!]

When I click the link in the following text of README.md

> We have a created a [colab intro (https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/misc/colab_intro.ipynb) notebook with more details.

I get the following error

> Notebook not found
> There was an error loading this notebook. Ensure that the file is accessible and try again.
> Ensure that you have permission to view this notebook in GitHub and authorize Colaboratory to use the GitHub API.
> 
> https://github.com/probml/pyprobml/blob/master/notebooks/misc/colab_intro.ipynb
> Could not find colab_intro.ipynb in https://api.github.com/repos/probml/pyprobml/contents/notebooks/misc?per_page=100&ref=master
> CustomError: Could not find colab_intro.ipynb in https://api.github.com/repos/probml/pyprobml/contents/notebooks/misc?per_page=100&ref=master
>     at new eK (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20221010-060050-RC00_480051506:2421:77)
>     at wa.program_ (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20221010-060050-RC00_480051506:2409:438)
>     at ya (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20221010-060050-RC00_480051506:20:336)
>     at wa.next_ (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20221010-060050-RC00_480051506:18:479)
>     at za.next (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20221010-060050-RC00_480051506:21:206)
>     at b (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20221010-060050-RC00_480051506:21:468)

I believe I authorized colab/github interaction correctly.

**Comment by nickdgardner** [comment]
Maybe the url should be the following (found on [this page](https://github.com/probml/pyprobml/blob/master/notebooks/tutorials/colab_gcp_tpu_tutorial.md))? 
https://colab.research.google.com/github/probml/probml-notebooks/blob/main/notebooks/colab_intro.ipynb

I can access that notebook just fine.

**Comment by murphyk** [comment]
It should be [colab intro](https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/tutorials/colab_intro.ipynb).
Fixed.
