### ISSUE TITLE
Figure 6.1 missing sub-figure c) showing a sequence logo.

### ISSUE THREAD

**Issue by paulhorton** [probml/pyprobml#1109]
Figure 6.1 b) shows a graphic depiction of a position frequency matrix, but it is not a sequence logo because all column heights are equal.  My guess is the original intent was to have a sub-figure 6.1 c) showing a sequence logo and compare that to the graphic in sub-figure 6.1 b)  so the reader can see how much easier it is to spot conserved positions when the column heights are scaled to equal the information content.   The text corresponding to figure 6.1 does mention heights scaled to information content (although "bar" height is used instead of "column" height.

**Comment by murphyk** [comment]
Solved in https://github.com/probml/pml-book/issues/581
