### ISSUE TITLE
Linear regression code includes calls to missing functions

### ISSUE THREAD

**Issue by thvasilo** [probml/pyprobml#13]
In examples like `linregPolyVsDegree.py` there are calls to a `preprocessor_create` function which seems to be part of an [old version](https://github.com/drgnrave/pmtk3/blob/76c1174447f262a30acda7345816d2956c18919c/python/utils/util.py#L79) of utils.util but has since been removed.

I guess we should bring back some of those functions to get the examples working again?

**Comment by murphyk** [comment]
Sure. Or better yet, re-do these examples using scikit learn, whcih
supports a lot of these preprocessors already.
(No need to re-invent the wheel.)

**Comment by thvasilo** [comment]
Cool, I'm in favor of using sklearn where possible as well.

I'll get this done this week.

**Comment by murphyk** [comment]
linregPolyVsDegree.py now works. It still relies on utils.util and is not yet based on scikit-learn. It would be great to remove depenence on utils.util...
