### ISSUE TITLE
Convert seqlogoDemo to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#187]
This is figure number 6.2 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/seqlogoDemo.m)

**Comment by ashishpapanai** [comment]
On it. @mjsML.

**Comment by ashishpapanai** [comment]
@murphyk, I've implemented the Dirichlet Sample and sample_Discrete functions in python, Is there any python counterpart for [seqlogoPmtk.m](https://github.com/murphyk/matlabtools/blob/master/graphics/seqlogoPmtk.m), I've found: [seqlogo](https://pypi.org/project/seqlogo/) but I don't know how reliable it will be.

**Comment by murphyk** [comment]
[seqlogo](https://pypi.org/project/seqlogo/) looks perfect.

**Comment by murphyk** [comment]
moved to hermes
