### ISSUE TITLE
Convert mixGaussMLvsMAP to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#194]
This is figure number 8.26 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/mixGaussMLvsMAP.m)

**Comment by murphyk** [comment]
Just need to modify this [EM for GMM](https://github.com/probml/pyprobml/blob/master/scripts/mix_gauss_demo_faithful.py) code to do MAP estimation instead of MLE.

**Comment by animesh-007** [comment]
Working on this.

**Comment by Drishttii** [comment]
Working on this.

**Comment by murphyk** [comment]
moved to hermes
