### ISSUE TITLE
Convert fisherLDAdemo to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#197]
This is figure number 9.5 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/fisherLDAdemo.m)

**Comment by Drishttii** [comment]
Hi, I am Drishti an outreachy applicant. I would like to work on this issue.

**Comment by mjsML** [comment]
> Hi, I am Drishti an outreachy applicant. I would like to work on this issue.

Please go ahead :)
