### ISSUE TITLE
Convert linregRobustDemoCombined to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#203]
This is figure number 11.9 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/linregRobustDemoCombined.m)

**Comment by ashishpapanai** [comment]
working on it. @mjsML

**Comment by murphyk** [comment]
The [robust linear models](https://www.statsmodels.org/stable/rlm.html) function from statsmodels should help with this example.
