### ISSUE TITLE
Convert ridgePathProstate to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#204]
This is figure number 11.12 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/ridgePathProstate.m)

**Comment by 3devRapeti** [comment]
I want to work on this.

**Comment by murphyk** [comment]
Just use [sklearn ridge regression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html#sklearn.linear_model.Ridge) with warm-starting as you sweep over the range of lambda.

**Comment by karalleyna** [comment]
I would like to work on this.

**Comment by mjsML** [comment]
> I would like to work on this.

please go ahead.
