### ISSUE TITLE
Convert lassoPathProstate to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#205]
This is figure number 11.12 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/lassoPathProstate.m)

**Comment by SondosAhmed** [comment]
I believe I can convert this Matlab code to python
@mjsML , I would like to work on this issue

**Comment by mjsML** [comment]
Sure go ahead.

**Comment by murphyk** [comment]
Just use the [sklearn lasso](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html) function
