### ISSUE TITLE
Convert sparseSensingDemo to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#206]
This is figure number 11.15 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/sparseSensingDemo.m)

**Comment by ashishpapanai** [comment]
@mjsML @murphyk , The Matlab code has a few issues as well:

Line number 51 to 52:
The dimensions of X: 1024 X 4096
Dimensions of y: 1024 X 1
Dimension of  X(:,ndx)\y; = 1024 X 1
```
wdebiased(ndx) = X(:,ndx)\y;
wfull = X'*y; % since X is orthogonal %pinv(X)*y; % X'*y; % X\y;
```
My conversion to Python:
```
for i in ndx:
    wdebiased[i] = np.divide(y.reshape(1024,), (X[:, 0]))  # flag
```
This is giving a broadcasting error which is correct as the dimension of wdebiased is 4094 X 1

I tried to run the MATLAB code in Octave and it gave a similar broadcasting error in line number 37:
```
% noisy observations
sigma = 0.01;
y = R*f + sigma*randn(k, 1);
```

**Comment by murphyk** [comment]
I think the [group lasso](https://pypi.org/project/group-lasso/) python package should help with this example.

**Comment by karalleyna** [comment]
Could I work on this?

**Comment by ashishpapanai** [comment]
Sure, I have implemented a few functions and a few were left, You can refer
the PR linked to the issue (if it is of any help)
