### ISSUE TITLE
Convert linregRbfDemo to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#212]
This is figure number 13.24 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/linregRbfDemo.m)

**Comment by nappaillav** [comment]
![image](https://user-images.githubusercontent.com/43855961/111992512-8542a200-8b3b-11eb-84cf-404a30f92ed6.png)
This is the figure that i'm getting @mjsML, the `KernelRidge(alpha=l, kernel='rbf')` works as expected  as `linregFit ` in this implementation. An help here could be very useful.

**Comment by mjsML** [comment]
@nappaillav I believe you'd need to revise the data generation portion. Also the right column is squished for some reason.

**Comment by nappaillav** [comment]
@murphyk @mjsML As per my understanding the prediction is not right. 
I'm trying to see the right replacement for `lineregfit` from the matlab code. Currently i'm using KernelRidgeregression function from sklearn. 
The data i.e generation is very similar to the one in the matlab figure 13.24

**Comment by mjsML** [comment]
@nappaillav I see 19 points on your graph while the matlab one has 21 :) (maybe the dots need to be bigger as per the original figure?) Also the distribution doesn't look quite the same (I have not looked at your code I'm just looking visually). 
The [example](https://scikit-learn.org/stable/modules/kernel_ridge.html) on sklearn cites @murphyk 1st edition 🙂 , I believe it should work 🙂
