### ISSUE TITLE
Convert mixexpDemoOneToMany to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#213]
This is figure number 13.25 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/mixexpDemoOneToMany.m)

**Comment by ashishpapanai** [comment]
Working on it.

**Comment by Prahitha** [comment]
Hello, I am an Outreachy applicant. Would love to work on this!

**Comment by murphyk** [comment]
I could not find any simple python implementation, so it will require coding the equations from scratch. (There seem to be a few SGD based implementations based on Tensorflow, but that is overly complex.)

**Comment by Prahitha** [comment]
Yes, I only realised after starting to work on it. I tried coding it from scratch but couldn't produce a similar result. Would it be okay if I choose some example that is not listed in the issues and work on a PR? Thanks!
