### ISSUE TITLE
Convert gprDemoChangeHparams to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#220]
This is figure number 17.9 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/gprDemoChangeHparams.m)

**Comment by ashishpapanai** [comment]
Working on it.

**Comment by ashishpapanai** [comment]
@mjsML 
I am unable to find any Python counterpart for the following functions:
`covfunc = {'covSum', {'covSEiso','covNoise'}};`
And it is not a very good idea to convert the MATLAB code of these three functions to Python, is there any suitable library/ code in your or @murphyk's knowledge?

**Comment by mjsML** [comment]
@ashishpapanai I'm not a matlab nor a GP expert, a small google search yielded [this](https://www.mathworks.com/matlabcentral/answers/10269-what-does-mean). and I believe those underlying functions should have equivalents in [scikit-learn ](https://scikit-learn.org/stable/modules/gaussian_process.html#gpr-examples) and even an attempt to mimic matlab convention [here](https://python.hotexamples.com/site/file?hash=0xddec81393c1b5ccdca64319b5fa99207b205917ef148449682585b2d39435b6a&fullName=MLO-master/model/regressors.py&project=CustomComputingGroup/MLO).
I hope this was helpful.

**Comment by Drishttii** [comment]
Hello, @ashishpapanai , I have tried solving this issue (#345 ). Please let me know if you have any suggestions. Thank you.

**Comment by murphyk** [comment]
Yes, #345 solved this.
