### ISSUE TITLE
Convert gprDemoMarglik to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#221]
This is figure number 17.10 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/gprDemoMarglik.m)

**Comment by Dsantra92** [comment]
Can I work on this?

**Comment by mjsML** [comment]
Please go ahead

**Comment by Drishttii** [comment]
@Dsantra92, I have tried solving this issue (#352). Please let me know if you have any suggestions. Thanks :)

**Comment by murphyk** [comment]
moved to hermes
