### ISSUE TITLE
Convert kernelBinaryClassifDemo to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#223]
This is figure number 17.22 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/kernelBinaryClassifDemo.m)

**Comment by vangorade** [comment]
code is using bishop2class data and also a lot of other examples, is it okay to use some other synthetic data

**Comment by mjsML** [comment]
@vangorade [I added the missing data ](https://github.com/probml/pyprobml/commit/1d08465b847827b41fd50229e9cee0797b80a914), you can use scipy.io mat functions to load it.

**Comment by always-newbie161** [comment]
Hi @mjsML,  I  would like to work on this, but can I get a clarification on how to find support vectors for L1-logreg ? and also should the decision boundaries be exact? I got some different contours.
