### ISSUE TITLE
Convert svmRegrDemo to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#224]
This is figure number 17.24 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/svmRegrDemo.m)

**Comment by aamirmiy** [comment]
@mjsML  I am trying to convert this example to python. Can you please tell me what  
"X = mkUnitVariance(centerCols(x))" this line means.

**Comment by always-newbie161** [comment]
Hi @murphyk,  @mjsML, I am working on this, for the 'svmqp' part Should I have to implement non-linear(rbf) SVM as a QP problem if yes can I use CVXPY ? as I am not able to find any readily available models in sklearn or any.

**Comment by mjsML** [comment]
> Hi @murphyk, @mjsML, I am working on this, for the 'svmqp' part Should I have to implement non-linear(rbf) SVM as a QP problem if yes can I use CVXPY ? as I am not able to find any readily available models in sklearn or any.

On a separate topic, could I ask you to please email admin@probml.ai ?

**Comment by always-newbie161** [comment]
> > Hi @murphyk, @mjsML, I am working on this, for the 'svmqp' part Should I have to implement non-linear(rbf) SVM as a QP problem if yes can I use CVXPY ? as I am not able to find any readily available models in sklearn or any.
> 
> On a separate topic, could I ask you to please email [admin@probml.ai](mailto:admin@probml.ai) ?

Ok, Is it about this doubt?

**Comment by mjsML** [comment]
> > > Hi @murphyk, @mjsML, I am working on this, for the 'svmqp' part Should I have to implement non-linear(rbf) SVM as a QP problem if yes can I use CVXPY ? as I am not able to find any readily available models in sklearn or any.
> > 
> > 
> > On a separate topic, could I ask you to please email [admin@probml.ai](mailto:admin@probml.ai) ?
> 
> Ok, Is it about this doubt?

As I mentioned unrelated but please do urgently.

**Comment by always-newbie161** [comment]
@mjsML  Done.

**Comment by murphyk** [comment]
moved to hermes
