### ISSUE TITLE
Convert pcaOverfitDemo to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#228]
This is figure number 20.8 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/pcaOverfitDemo.m)

**Comment by animesh-007** [comment]
I would like to work on this.

**Comment by mjsML** [comment]
@animesh-007 I didn't know about gitter 🙂 . I know about slack but for public channels, I'm from the IRC days. I'll explore gitter and let you know if we could use a gitter room for the repo given the time constraints.

**Comment by animesh-007** [comment]
> @animesh-007 I didn't know about gitter 🙂 . I know about slack but for public channels, I'm from the IRC days. I'll explore gitter and let you know if we could use a gitter room for the repo given the time constraints.

Even I don't like gitter that much personally😅.  If it okay could you set up a slack channel for this repo? So that we can communicate and also ask our queries on GSoC project.😊

**Comment by animesh-007** [comment]
@mjsML In the Matlab implementation they have used the `mnistAll` dataset. I was not able to find the same in this repo.
Could you provide the same?

**Comment by mjsML** [comment]
Hi @animesh-007 
Based on the numbers of examples I suspect this is just your [standard mnist](https://www.tensorflow.org/datasets/catalog/mnist). I believe the loadData function is referring to [this directory](https://github.com/probml/pmtk3/tree/master/bigData/mnistAll). I would load both the 'modern' one (i.e. provided by your library of choice as a toy dataset) and the one on pmtk3 in mat format and compare even visually.

I hope this helps.
M

**Comment by Nirzu97** [comment]
Hi, @mjsML and @murphyk,

I am an outreachy applicant. I am very excited to contribute in this project. I have created pull request for this issue. It's my first time contributing in open source. Please let me know if I make some mistakes. Your feedbacks will be very helpful.

While working on this issue I have noticed that Figure 20.6 and 20.7 also do not have Python code. If possible can you open issues for that. I would love to work on it too. Thank you.
