### ISSUE TITLE
estimate mutual information for all pairs of WHO variables

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#321]
Reproduce fig 6.5 using [sklearn.mutual_info_regression](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.mutual_info_regression.html) instead of the MIC coefficient.
The 357 health and economic variables  are from the Science paper [Detecting Novel Associations in Large Data Sets](https://science.sciencemag.org/content/334/6062/1518). (Cached copy of pdf is [here](https://www.researchgate.net/publication/51884204_Detecting_Novel_Associations_in_Large_Data_Sets))

The new figure should look something like this:
<img width="665" alt="fig6-5-MI-WHO" src="https://user-images.githubusercontent.com/4632336/112757743-ecc77a00-8f9f-11eb-995e-c3f7b4398c21.png">

**Comment by nappaillav** [comment]
@murphyk 

I could not find the corresponding dataset, as the link above need paid account to access the Data and figures. I have searched for the dataset elsewhere but could not find the right link. 
If its possible to share some downloadable link, it could be really helpful

With that I can start working on reproducing the Figure.

**Comment by animesh-007** [comment]
Hi @murphyk.
I was looking for the required dataset and found this on one site. Could you confirm once whether this dataset is correct or not?
[Dataset](https://data.world/resiport/who-dataset)

**Comment by nappaillav** [comment]
@animesh-007 I already started working on this problem, can you give me a days time. If by then I'm not able to solve it you can take it up. To avoid clash of work. 
Kind request :)

**Comment by animesh-007** [comment]
> @animesh-007 I already started working on this problem, can you give me a days time. If by then I'm not able to solve it you can take it up. To avoid clash of work.
> Kind request :)

Sure. Good luck with this. I hope you were able to get the required dataset for this issue. 😇

**Comment by mjsML** [comment]
@animesh-007 @nappaillav maybe you could both [collaborate](https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) on this?

**Comment by nappaillav** [comment]
@animesh-007 that Sounds fine to me. 
@mjsML Nice idea :)

**Comment by animesh-007** [comment]
> @animesh-007 that Sounds fine to me.
> @mjsML Nice idea :)

Sure. Count me in. @nappaillav 😊

**Comment by murphyk** [comment]
I read some more about the MIC statistic, and how the original figure was created. The paper makes the case that the sklearn.mutual_info_regression estimator will not work as well as MIC, which may be related to  your odd plot. So I think you should  just check in what you have, and stop working further on this,  and I will close the issue. Sorry for the red herring.

**Comment by animesh-007** [comment]
> I read some more about the MIC statistic, and how the original figure was created. The paper makes the case that the sklearn.mutual_info_regression estimator will not work as well as MIC, which may be related to your odd plot. So I think you should just check in what you have, and stop working further on this, and I will close the issue. Sorry for the red herring.

No problem.😊
