### ISSUE TITLE
make JAX implementation of SVI for mixture models

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#348]
Stochastic Variational Inference can be used to do online optimization of Bayesian/latent variable models, such as finite mixtures of Gaussians / Bernoullis - this is faster than batch EM for large datasets. [Here](https://brendanhasz.github.io/2019/06/12/tfp-gmm.html) is an implementation of SVI for GMMs in Tensorflow Probabiltity. The goals of this issue are:
1. make a JAX translation of this code, using the new [distrax library](https://github.com/deepmind/distrax).
2. generalize the code to work with mixtures of Bernoullis, apply it to the same binarized MNIST data used in [mixBerMNIST.py](https://github.com/probml/pyprobml/blob/master/scripts/mixBerMnistEM.py)

**Comment by shivaditya-meduri** [comment]
Hi @murphyk, I will start working on it!

**Comment by shivaditya-meduri** [comment]
Thank you for the link  of "Bayesian Gaussian Mixture Modeling with Stochastic Variational Inference", it is very helpful

**Comment by murphyk** [comment]
This blog post has some of useful background on SVI for GMMs: https://ypei.me/posts/2019-02-14-raise-your-elbo.html. I will cover some of this in vol 2 of my book, but that's not ready for sharing yet.

**Comment by shivaditya-meduri** [comment]
Thank you @murphyk, I will start implementing SVI for BMM

**Comment by Nirzu97** [comment]
@shivaditya-meduri  Are you still working on this?

**Comment by shivaditya-meduri** [comment]
If you want to contribute that would be great, I will create a draft PR and you can look at the code I made till now

**Comment by shivaditya-meduri** [comment]
I have completed task 1, it is the task 2 I could use your help with, and after that I will add your name as a collaborator :). Thank you
I wanted to upload only one commit for both the tasks, That's why I did not commit till now for the task 1
