### ISSUE TITLE
refactor matrix-factorization notebook

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#357]
The [matrix_factorization_recommender](https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/matrix_factorization_recommender.ipynb) colab has 2 main parts: the first is pure numpy , the second uses the surprise library, since they are distinct.
The goal is to split this into 2 separate colabs.
Note:The first part  downloads extra data containing title and genre for each movie, so we can decode integer codes into something meaningful (see eg `get_movie_name` and `get_movie_genres`). This will need to be copied to the second colab.

**Comment by Nirzu97** [comment]
working on this

**Comment by karalleyna** [comment]
@Nirzu97  if you need help, please let me know. I would like to be happy if I work on this too.
