### ISSUE TITLE
use jax.numpy consistently 

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#358]
Currently several pieces of code use the following deprecated convention
```
import jax
import jax.numpy as np # redefines the np name
import numpy as onp # original numpy
```
This should be changed to the new convention
```
import jax
import jax.numpy as jnp
import numpy as np # original numpy, standard name
```
Known notebooks where this occurs and needs fixing:
- [linalg.ipynb](https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/linalg.ipynb)
- [logreg_jax.ipynb](https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/logreg_jax.ipynb)
-
Known scripts  where this occurs and needs fixing:
- autodiff_demo.py
- autodiff_demo_jax.py
- autodiff_logreg.py
- bayenet_inf_autodiff.py
- iris_optimize.py
- mean_shift_opt.py
- rbf_2d_plot.py
- student_pgm_inf_autodiff.py
- ugm_inf_autodiff.py
-

**Comment by ashishpapanai** [comment]
Working on it.

**Comment by Drishttii** [comment]
Working on this.

**Comment by murphyk** [comment]
Please make a new issue for each file that needs converting, and tackle them one by one, so each PR has a single file in it.

**Comment by Nirzu97** [comment]
Hi, @Drishttii, I want to work on this too. Can we collaborate on this?

**Comment by Drishttii** [comment]
> Please make a new issue for each file that needs converting, and tackle them one by one, so each PR has a single file in it.

Yes @murphyk will do that. Thanks. 

> Hi, @Drishttii, I want to work on this too. Can we collaborate on this?

Hello @Nirzu97 , I will let you know if I am unable to do this. Thank you very much.

**Comment by murphyk** [comment]
Thanks, guys, all of the scripts now seem to correctly use `import jax.numpy as jnp` :)
