### ISSUE TITLE
convert autoencoder mnist demo from TF2 to pytorch and/or JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#359]
[ae_mnist_tf](https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/ae_mnist_tf.ipynb) should be converted to pytorch and/or JAX.

**Comment by kimbochen** [comment]
Hi, @murphyk, I would like to work on this.

**Comment by always-newbie161** [comment]
@kimbochen, let me know if you are working, I am working on this

**Comment by kimbochen** [comment]
Yes, I am working on this. Sorry for not expressing myself clearly.  
This is my first time trying to contribute, would you mind explaining a better way to communicate?

**Comment by always-newbie161** [comment]
@kimbochen okay Carry on, there isn't any communication channel right now, comment thread for an issue(or PR) is the  only way to communicate.
