### ISSUE TITLE
convert VAE celeba demo from TF2 to pytorch and/or JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#360]
Convert [vae_celeba_tf.ipynb](https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/vae_celeba_tf.ipynb) to pytorch and/or JAX.
Also convert [vae_mnist_gdl_tf.ipynb](https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/vae_mnist_gdl_tf.ipynb).
(Why do we have 2 demos?)
Note: code should work for any kind of image, eg gray scale MNIST or color celebA, so don't hard-code image dimensions into the model.

**Comment by Nirzu97** [comment]
I want to work on this

**Comment by always-newbie161** [comment]
Working on this.
