### ISSUE TITLE
Porting the complete book code to Python?

### ISSUE THREAD

**Issue by thvasilo** [probml/pyprobml#4]
Hello Kevin,

I was wondering if there is a plan to port all of the code examples from the ML book to Python?

If that's the case I'd love to help out :)

**Comment by murphyk** [comment]
Yes, I am hoping to do that.  I am including a list of all the
matlab-generated figures from the new introductory chapter.
It would be great if you could make python equivalents of these...

\figgen{\codename{gaussPlotDemo}}.

\figgen{\codename{gaussPlot2Ddemo}}.

\figgen{\codename{binomDistPlot}}.

\figgen{\codename{discreteProbDistFig}}.

\figgen{\codename{binomialBetaPosteriorDemo}}.

##See \Pycodename{betaCredibleInt}.  # Already python

\figgen{\codename{betaBinomPostPredDemo}}.

\figgen{\codename{lossFunctionFig}}.

\figgen{\codename{linregWedgeDemo2}}.

\figgen{\codename{linregResiduals}}.

\figgen{\codename{linregPolyVsDegree}}.

    Produced by \codename{surfaceFitDemo}.

\figgen{\codename{contoursSSEdemo}}.

\figgen{\codename{bayesLinRegDemo2d}}.

\figgen{\codename{linregPostPredDemo}}.

\figgen{\codename{sigmoidPlot}}.

\figgen{\codename{logregSATdemo}}.

\figgen{\codename{logregBinarydemo}}.

\figgen{\codename{sigmoidplot2D}}.

\figgen{\codename{logregBinarydemo}}.

   \figgen{\codename{softmaxDemo2}}.

\figgen{\codename{logregMultinomKernelDemo}}.

\figgen{\codename{fisheririsDemo}}.

\figgen{\Pycodename{logregIrisDemo}}.

\figgen{\codename{newsgroupsVisualize}}.

\figgen{\codename{shuffledDigitsDemo}}.

\figgen{\codename{dtreeDemoIris}}.

\figgen{\codename{regtreeSurfaceDemo}}.

\figgen{\codename{linregPolyVsN}}.

\figgen{\codename{knnVoronoi}}.

\figgen{\codename{knnClassifyDemo2}}.

\figgen{\codename{logregBinaryDemo}}.

 \codename{mnist1NNdemo},

\figgen{\codename{curseDimensionality}}.

\figgen{\codename{linregRbfDemo}}.

\figgen{\codename{logregBinarydemo}}.

\figgen{\codename{linregEbModelSelVsN}}.

%\figgen{\codename{kmeansHeightWeight}}.

\figgen{\codename{mixGaussDemo2d}}.

\figgen{\codename{kmeansYeastDemo}}.

\## figgen{\Pycodename{PCA-Biplot-Demo}}. # already python

\figgen{\codename{ggmLassoDemo}}.

**Comment by thvasilo** [comment]
Sure, I'll get started this week. Just note that it's internship hunting season now so I'll be a bit slow :)

**Comment by thvasilo** [comment]
I did some initial investigation today, namely created a list of files that already have a Python version from the list you gave above, and checked which of those will run currently.

From what I see most of the figures in the above list already have a Python implementation (I just did a matching filename search). I have a Gdoc with the status [here](https://docs.google.com/spreadsheets/d/1biOojjV6O1h9ysCVkQgIIqZ7ea5SMs9LAk5o4HmrPwc/edit?usp=sharing).

Some of the examples will currently not run, because they depend on `utils.util`, which tries to import `init_pmtk3` which I'm not able to find in this or the `pmtk3` repo. Maybe it was removed when moving repos?

There are other minor problems, like the fact that the Lena image was [removed from scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.lena.html), but most of the implemented examples seems to run with the current state of the repo.

Also, am I correct to assume code should be written in Python 3, hence I'd need to change `print` statements etc?

**Comment by murphyk** [comment]
This is great, thank you.
If you can tweak the scripts so that they run, including in python3, that
would be great!

**Comment by codewatson** [comment]
Hi Theodore,
Can you please help explain how you ran through the python examples?? did you write some script?I was trying to run linearegPolyVsDegree.py and it required the utils.util importing init_pmtk3 but in the gsheet it seems to be working.
I can help with the porting of code aswell. We are following the book in our class this semester.

**Comment by thvasilo** [comment]
Hello @codewatson. 

For running the examples I simply used `for i in $(ls *.py) ; do python $i ; done` in the `examples` directory.

As I said above some of the examples will not run, specifically those that try to import `utils.util` which in turn tries to import `init_pmtk3`. I had been trying to find an `init_pmtk3` file in previous versions of the code but I've been unsuccessful. Maybe @murphyk knows what's up with that, my guess is it was removed at some point.

If you want to help feel free to take one of the examples that currently does not have an implementation, put your name in the responsible field so we don't have duplicate work, and you can open a PR when you are done.

I'm currently busy with interview prep, but will start with this on the weekend.

**Comment by codewatson** [comment]
Hi,
Sure I'll update the sheet for the examples for which I can take up the responsibility.

**Comment by murphyk** [comment]
On Tue, Sep 20, 2016 at 9:49 AM, Theodore Vasiloudis <
notifications@github.com> wrote:

> I did some initial investigation today, namely created a list of files
> that already have a Python version from the list you gave above, and
> checked which of those will run currently.
>
> From what I see most of the figures in the above list already have a
> Python implementation (I just did a matching filename search). I have a
> Gdoc with the status here
> <https://docs.google.com/spreadsheets/d/1biOojjV6O1h9ysCVkQgIIqZ7ea5SMs9LAk5o4HmrPwc/edit?usp=sharing>
> .
>
> Some of the examples will currently not run, because they depend on
> utils.util, which tries to import init_pmtk3 which I'm not able to find
> in this or the pmtk3 repo.
>

I have just fixed this. I can't remember who pushed this change, but the
goal is to have no dependence on the old matlab code. I have copied over
the relevant data files and added them to the repo.

**Comment by themantalope** [comment]
Hi All!

I'm a huge fan of the book, let me know if you need more help with the examples. Is the google spreadsheet up to date?

**Comment by thvasilo** [comment]
Hello @themantalope, the doc is up to date yes, I've been working on getting the current examples to work and porting to Python 3 so I haven't worked on a new problem. 

Feel free to take up one of the tasks listed, just make sure to open an issue describing what you are working on so it's easier to keep track (better to have Github as the single source of truth)

**Comment by themantalope** [comment]
Great! I'll start taking a look this weekend.

**Comment by murphyk** [comment]
Right now I'm focusing on writing the 2nd edition of the book.
Translating legacy code from matlab to python is lower priority (although whenever I make a new demo, I try to write it in python.) Once the new edition comes out (hopefully 2019), there will lots of readers who can help with this translation effort :)
