### ISSUE TITLE
examples/linregPolyVsDegree.py broken

### ISSUE THREAD

**Issue by krkeane** [probml/pyprobml#41]
The code refers to example/linearRegression.py  which was renamed examples/linregPmtkEmulator.py [here](https://github.com/probml/pyprobml/commit/522f51753cdf03edc6172c2e5b08dfa39cffa780#diff-b73f57105504560691d0c586ba722868).

Minor PR to follow.

**Comment by murphyk** [comment]
I just pushed a fix for this (leverages linregPmtkEmulator from krkeane)
