### ISSUE TITLE
make prostateComparison.py plot (compares L1, L2 and subset selection)

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#450]
Convert [prostateComparison.m](https://github.com/probml/pmtk3/blob/master/demos/prostateComparison.m) to python. Most of the code is already written: see [lassoPathProstate.py]https://github.com/probml/pyprobml/blob/master/scripts/lassoPathProstate.py)
and [ridgePathProstate.py](https://github.com/probml/pyprobml/blob/master/scripts/ridgePathProstate.py).
Just need to add subset selection, and make the table of numbers. This corresponds to fig 11.13 of [v1.0 of vol1](https://github.com/probml/pml-book/releases/tag/v1.0).

**Comment by Nirzu97** [comment]
Working on this.

**Comment by murphyk** [comment]
moved to hermes
