### ISSUE TITLE
visualize posterior marginals of a discrete graphical model

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#458]
The [asia_pgm.ipynb](https://github.com/probml/pyprobml/blob/master/notebooks/asia_pgm.ipynb) notebook computes posterior marginals in a small, discrete graphical model (known as the "Asia" network) using the [pgmpy package](https://pgmpy.org/). The task is to visualize these posterior marginals on top of the graph itself, similar to the picture below. 
(This corresponds to 4 different evidence sets, as explained in the colab.)

![Screen Shot 2021-05-19 at 12 24 12 PM](https://user-images.githubusercontent.com/4632336/118872284-40b65700-b89d-11eb-8739-bc94fce6808a.png)

Since rendering histograms may be hard, a simpler solution is just to print the marginals in text form inside the nodes.
eg replace the string "Asia" with "Asia (0.5, 0.5)", to mean that there is 50% probability that Asia=0, and 50% probability that Asia=1. The main tricky bit is to figure out how to modify the dot file generated by [graphviz](https://pypi.org/project/graphviz/). The [numpyro site](https://numpyro.readthedocs.io/en/latest/tutorials/model_rendering.html) has some relevant material.

The code should work for any graph structure. In particular, after getting it working on the Asia network, please also apply it to the [student network](https://github.com/probml/pyprobml/blob/master/notebooks/student_pgmpy.ipynb).

**Comment by Drishttii** [comment]
Working on this ....

**Comment by murphyk** [comment]
fixed in pgmpy_utils
