### ISSUE TITLE
visualize CPTs for discrete graphical model 

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#459]
In the [student_pgmpy.ipynb](https://github.com/probml/pyprobml/blob/master/notebooks/student_pgmpy.ipynb), we show the conditional probability tables (CPTs) for each node in graphical model, in addition to the graph structure, as shown below.

![student-dgm](https://user-images.githubusercontent.com/4632336/118884310-21bec180-b8ab-11eb-81cf-481553c21d8a.png)

The goal of this task is to automate this process. The graph rendering can be done using graphviz, as illustrated in the notebook. The challenge is to figure out how to attach extra text information to the resulting graph (perhaps as dummy nodes?).

This issue is related to #458 but different - that issue just shows the nodes and their posterior marginals.
This issue is concerned with showing the parameters of the network.

**Comment by Drishttii** [comment]
Working on this ....

**Comment by murphyk** [comment]
As in #458, once you have gotten your CPT visualization code working, please add it to [pgmpy_utils.py](https://github.com/probml/pyprobml/blob/master/scripts/pgmpy_utils.py) and then call it from both the asia and student networks.

**Comment by murphyk** [comment]
fixed
