### ISSUE TITLE
create noninformative prior for logistic regression in high dimensions

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#463]
In fig 3 of [the Bayesian workflow paper](https://arxiv.org/pdf/2011.01808.pdf), they show that a standard 'uninformative' Gaussian prior on the weights of a logistic regression model induces a very strong prior that the output response, when applied to random binary data, is either 0 or 1 with high probability; so this is not uninformative after all. Some code to reproduce this plot is [here](https://github.com/probml/pyprobml/blob/master/scripts/logreg_prior.py). 

The task is to figure out some way to scale the prior variance to ensure the output response is roughly uniform on the [0,1] scale, even as the number of dimensions increases. This may require scaling the standard deviation by D or sqrt(D), and/or switching to another prior, such as a student T.

**Comment by Neoanarika** [comment]
I am working on this

**Comment by murphyk** [comment]
I just moved this to hermes
