### ISSUE TITLE
2d blind deconvolution  with PGMs

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#670]
Reimplement the the 2d blind deconvolution example from the "Perturb and Max Product" paper (sec 5.6 of https://arxiv.org/pdf/2111.02458.pdf)

**Comment by murphyk** [comment]
the original JAX code is linked at https://github.com/vicariousinc/PGMax/issues/112.
It would be useful to rewrite this to use the PGMax library, and convert to a self-contained colab.

**Comment by computational-shenanigans** [comment]
Hi @murphyk , I would like to take this up!

**Comment by murphyk** [comment]
Solved in https://github.com/vicariousinc/PGMax/pull/127
