### ISSUE TITLE
implement hierarchical Gaussian filter

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#671]
Reimplement the bandit model from paper below.  (This is a hierarchical latent variable model where the mean and variance of each Gaussian rv is a (nonlinear) function of the layer above.)

C. D. Mathys et al., “Uncertainty in perception and the Hierarchical Gaussian Filter,” Front. Hum. Neurosci., vol. 8, p. 825, Nov. 2014, doi: 10.3389/fnhum.2014.00825. [Online]. Available: http://dx.doi.org/10.3389/fnhum.2014.00825

**Comment by workatcam** [comment]
Hey Kevin, can you point out which chapters may have this content in your book?

**Comment by murphyk** [comment]
I don't actually discuss this algorithm in the book, so I am going to close this issue, since there are more important things to do :)
