### ISSUE TITLE
update score matching JAX demo

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#673]
The  chapter on energy based models currently only has [one demo ](https://colab.research.google.com/github/probml/probml-notebooks/blob/master/notebooks/score_matching_swiss_roll.ipynb), which does score matching on 2d swiss roll data. This uses deprecated JAX libraries like jax.stax and jax.experimental.optmizers. Please update code to use flax and optax.

**Comment by arihantbansal** [comment]
I would like to take this up

**Comment by murphyk** [comment]
Hi @arihantbansal . Sure, go for it.
See  fig 25.3 of [vol 2](https://probml.github.io/pml-book/book2.html) for some details.
