### ISSUE TITLE
make pedagogical JAX EBM demos

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#674]
The  chapter on energy based models currently only has [one demo ](https://colab.research.google.com/github/probml/probml-notebooks/blob/master/notebooks/score_matching_swiss_roll.ipynb), which does score matching on 2d swiss roll data. 
We need more pedagocial examples, eg of contrastive divergence learning, or fitting EBMs to MNIST.
Maybe translate the [Learnergy pytorch ](https://github.com/gugarosa/learnergy) code to JAX?

**Comment by murphyk** [comment]
See ch 25  of [vol 2](https://probml.github.io/pml-book/book2.html) for some details.

**Comment by itsanjukumar** [comment]
@murphyk  Hi, i would like to work on this issue.

**Comment by gileshd** [comment]
If it wouldn't be stepping on anyone's toes, I'd like to give this a go too. 
I was thinking of starting with a simple example of contrastive divergence for a RBM, time permitting, this might be extended to using persistent CD for pre-training a DBM.

**Comment by coding-geek1711** [comment]
@gileshd I am also planning to work on this. But will work on something other than Contrastive Divergence for RBM. Just keeping you in the loop. At the moment, working on fitting EBMs to MNIST.
