### ISSUE TITLE
Make a  JAX GAN demo in Colab

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#675]
Take some of the examples from https://github.com/valentingol/GANJax (eg pretrained CIFAR) model and convert to  a self-contained colab.

**Comment by itsanjukumar** [comment]
@murphyk  Please assign this issue to me. Thank you!

**Comment by susnato** [comment]
Hey, I would like to take this issue up.

**Comment by murphyk** [comment]
Hi @susnato . Sure, go for it.

**Comment by murphyk** [comment]
See ch 27  of [vol 2](https://probml.github.io/pml-book/book2.html) for some details.
