### ISSUE TITLE
implement causal impact using JSL

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#676]
Reimplement the TFP code at https://github.com/WillianFuks/tfcausalimpact using the [Jax SSM library](https://github.com/probml/JSL)

**Comment by adityamwagh** [comment]
@murphyk I can try to do this. It's similar to bayesian filtering right?

**Comment by murphyk** [comment]
Yes, I describe the high level idea in 19.3.5 of [vol 2](https://probml.github.io/pml-book/book2.html), but you should read the [original paper](https://github.com/google/CausalImpact) for details. Note you first need to solve #687 (which in itself is a large task).

**Comment by adityamwagh** [comment]
Okay! I will have a look.
