### ISSUE TITLE
add backwards sampling to kalman_smoother code 

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#678]
Implement a function to draw a sample path from the smoothed posterior. Add to https://github.com/probml/JSL/blob/main/jsl/lds/kalman_filter.py

**Comment by murphyk** [comment]
See sec 8.4.4 of [vol 2](https://probml.github.io/pml-book/book2.html) for details.
The book only covers Kalman smoothing, implemented [here](https://github.com/probml/JSL/blob/main/jsl/lds/kalman_filter.py),
but the sampling code is similar.
You should check correctness of your method by comparing to
https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/LinearGaussianStateSpaceModel#posterior_sample

**Comment by apoorvagnihotri** [comment]
I would like to work on this. I have had experience with Kalman Filters in a stint.

**Comment by xinglong-li** [comment]
I'd like to have a look at this issue ;)

**Comment by xinglong-li** [comment]
Hi @murphyk, 
I've implemented the sampling algorithm from the smoothed posterior, but I'm not able to push to that repo, nor could I attach my file hear.
So please review my code in the colab via the following link:

https://colab.research.google.com/drive/1BdVj-ga9Ou0a_cxSggcC8gwOZwoL9MBZ#scrollTo=3EddiXYzMISl

**Comment by murphyk** [comment]
Hi @xinglong-li  Please open a pull request at https://github.com/probml/JSL for the core `kalman_sampler.py` function (put it in jsl/lds) and then add the demo (and comparison to TFP) to `jsl/demos/lds_sampling_demo.py`.

**Comment by xinglong-li** [comment]
Hi @murphyk, it's done!
Please take a review of my code. https://github.com/probml/JSL/pull/37
