### ISSUE TITLE
implement deep kalman filter in JSL

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#679]
Convert the [pyro demo](https://pyro.ai/examples/dmm.html), which uses pytorch under the hood, to numpyro, which uses jax under the hood. Use flax for the neural network part. Then reimplement in pure jax/flax, without relying on numpyro black magic.

**Comment by gr8geek** [comment]
@murphyk please assign me this issue.

**Comment by murphyk** [comment]
@gr8geek . Feel free to start working on this. See sec 31.5.1 of [vol 2](https://probml.github.io/pml-book/book2.html) for details.

**Comment by UmarJ** [comment]
@peterchang0414, sorry for not leaving a comment earlier, but I have translated the tutorial to `numpyro`. I am working on converting it to pure JAX. If you haven't made progress on this issue, then I'd like to continue working on it :)

**Comment by peterchang0414** [comment]
@UmarJ Sure, no problem, I'll work on a different issue. Good luck!
