### ISSUE TITLE
implement Bayesian Online Changepoint Detection in JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#680]
The first goal is to make a JAX version of this numpy code: https://github.com/gwgundersen/bocd/
The second goal is to  implement the sparse particle filter variant of BOCPD in Liu and Fearnhead (https://eprints.lancs.ac.uk/id/eprint/745/) since it is much more efficient for long sequences. Use this to reproduce their fig 1, that does online CPD for conjugate linear regression models.

**Comment by bicycleman15** [comment]
Hey @murphyk, I would like to take this up 😄

**Comment by murphyk** [comment]
Hi @bicycleman15 . Actually @gerdm  is already working on this. Please pick another topic for now.
