### ISSUE TITLE
make JAX version of ladder VAEs

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#681]
Convert this PyTorch code to JAX: https://github.com/addtt/ladder-vae-pytorch

**Comment by murphyk** [comment]
See also this pytorch version: https://github.com/AntixK/PyTorch-VAE/blob/master/models/lvae.py

**Comment by codeboy5** [comment]
Hey, I would like to take this issue up.
Thanks

**Comment by murphyk** [comment]
Hi @codeboy5 . Sure, please go for it. See sec 22.5 of [vol 2](https://probml.github.io/pml-book/book2.html) for details.
