### ISSUE TITLE
Figure 4.10 - Confusion in likelihood

### ISSUE THREAD

**Issue by patel-zeel** [probml/pyprobml#683]
![image](https://user-images.githubusercontent.com/59758528/157498555-f5635a18-852a-481e-b5ae-67fed7a168ab.png)

Figure 4.10 caption says that:
> Updating a Beta prior with a Bernoulli likelihood...

Given that the Bernoulli likelihood can not be greater than 1 at any point, I checked [the code](http://figures.probml.ai/book1/4.10) and found that Beta (with `dirichlet`) is used for the likelihood (as correctly mentioned in the legend). I think if the Bernoulli likelihood was plotted then it would not exactly superimpose on the posterior in Figure 4.10 (b). Please let me know if I am missing something here.

**Comment by gerdm** [comment]
Hi @patel-zeel,

You're correct in that the likelihood for the Bernoulli cannot be greater than one. However, plot is shown up to a term *proportional* to the Bernoulli likelihood, i.e., the pdf of the Beta distribution.

**Comment by patel-zeel** [comment]
Thank you for clarification, @gerdm. Maybe this detail can be incorporated somehow to avoid confusion between legend and caption.

**Comment by murphyk** [comment]
Hi @patel-zeel . You are right, this is confusing. I didn't write that script - it has several problems (very non-pythonic, etc). Would you like to fix it?

**Comment by patel-zeel** [comment]
Sure, Prof. @murphyk. Is it fine if a secondary y-axis is created to show the likelihood due to a huge difference in the range between likelihood and prior/posterior? for example: 

![image](https://user-images.githubusercontent.com/59758528/157614359-d6162901-1cea-4cdd-b91a-6b33239b74b9.png)

**Comment by murphyk** [comment]
This looks great! Do you want to make a PR?

**Comment by patel-zeel** [comment]
Sure, Prof. @murphyk. I have opened a PR. Thank you for the review!
