### ISSUE TITLE
implement (variational) message passing for forney factor graphs

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#684]
Implement the algorithms desribed in this paper:

M. Cox, T. van de Laar, and B. de Vries, “A factor graph approach to automated design of Bayesian signal processing algorithms,” Int. J. Approx. Reason., vol. 104, pp. 185–204, Jan. 2019, doi: 10.1016/j.ijar.2018.11.002. [Online]. Available: http://www.sciencedirect.com/science/article/pii/S0888613X18304298

See the following Julia codebase for details:
https://github.com/biaslab/ForneyLab.jl

See also sec 9.3 of [vol 2](https://probml.github.io/pml-book/book2.html) for background material.

**Comment by pat749** [comment]
hi @murphyk i would like to work on this .is it still free and what are the prerequisites for it ?thanks.

**Comment by murphyk** [comment]
@pat749 Yes this is still available. Note that this is a very large task! You need to first break it down into smaller pieces and make a roadmap. I would suggest starting with a Forney FG version of Gaussian BP in #696 (both methods should give same results). But make the API generic so you can also handle discrete messages, and then add other exponential family messages over time.

**Comment by pat749** [comment]
ok sir
