### ISSUE TITLE
Implement structural time series models in JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#687]
Convert the [TF STS module](https://www.tensorflow.org/probability/api_docs/python/tfp/sts) to JAX, leveraging our
existing [Jax SSM code](https://github.com/probml/JSL). See sec 19.3.1 of  [vol 2](https://probml.github.io/pml-book/book2.html) for an overview of STS methods.
Note: it is standard to fit STS models using (blocked) Gibbs sampling, so you first need to wait until #677 is solved.

**Comment by BitterKanegul** [comment]
Hey, 
I would like to be a part of this implementation chain.
Thanks.

**Comment by murphyk** [comment]
Hi @BitterKanegul . Please go for it. But note that there are many prerequisite tasks that need to be solved first.

**Comment by BitterKanegul** [comment]
Thank you! I'll try to build the skeleton and start working on the missing pieces. Lots of amazing folks already at it!
