### ISSUE TITLE
More GSOC issues - avoid reinventing the wheel?

### ISSUE THREAD

**Issue by workatcam** [probml/pyprobml#689]
Hey Kevin, thanks for your tasks! May I kindly ask would you mind if multiple people work on the same issue or if it is possible to have more tasks? @murphyk

**Comment by murphyk** [comment]
Hi @workatcam . I don't have the cycles to create (and code review) more issues right now, but if you want to propose some new issues, please do so.

**Comment by workatcam** [comment]
Thanks a lot, Kevin!
