### ISSUE TITLE
exact 1d Bayesian filtering

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#692]
Replicate the examples in the paper below using JAX.

@INPROCEEDINGS{Roth2017icassp,
  title     = "Computation and visualization of posterior densities in scalar
               nonlinear and non-Gaussian Bayesian filtering and smoothing
               problems",
  booktitle = icassp,
  url = 
https://liu.diva-portal.org/smash/get/diva2:1173608/FULLTEXT02.pdf
  author    = "Roth, M and Gustafsson, F",
  pages     = "4686--4690",
  month     =  mar,
  year      =  2017
}

**Comment by dilithjay** [comment]
There seems to be an issue with the URL (at least for me). It says `Could not read metadata or incorrect PID`.

**Comment by murphyk** [comment]
Corrected URL: https://liu.diva-portal.org/smash/get/diva2:1173608/FULLTEXT02.pdf

**Comment by benlau6** [comment]
Hi @murphyk, I would like to work on this issue.
Thank you.

**Comment by murphyk** [comment]
Added to https://github.com/probml/probml-notebooks/blob/main/notebooks/discretized_ssm.ipynb
