### ISSUE TITLE
convert pytorch Gaussian belief propagation to JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#696]
Convert the code in [this colab](https://colab.research.google.com/drive/1-nrE95X4UC9FBLR0-cTnsIP_XhA_PZKW?usp=sharing#scrollTo=Y4gutLjG5_-L) to JAX.  This colab implements the 1d line fitting demo described in  https://gaussianbp.github.io.

Details of the model and algorithm are available in this paper:

A. J. Davison and J. Ortiz, “FutureMapping 2: Gaussian Belief Propagation for Spatial AI,” arXiv [cs.AI], Oct. 30, 2019 [Online]. Available: http://arxiv.org/abs/1910.14139

I would recommend writing the code functionally (not using object oriented style), so it can be more easily jit'd for speed.

As a bonus item, I recommend checking the correctness of your code by comparing it to [kalman smoother](https://github.com/probml/JSL/blob/main/jsl/lds/kalman_filter.py#L127) for a chain-structured factor graph with Gaussian factors.

**Comment by codeboy5** [comment]
Working on this issue. Thanks !

**Comment by murphyk** [comment]
@moloydas just sent me his code for this, which we will check in soon, so I don't need anyone else to work on it :)
