### ISSUE TITLE
convert logspace TF notebook to JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#697]
Convert this short notebook to JAX:
https://github.com/probml/probml-notebooks/blob/main/notebooks/logspace_tf.ipynb

**Comment by BitterKanegul** [comment]
Hi, I would like to take this up. 
Thank you!

**Comment by murphyk** [comment]
@BitterKanegul I think what you have is fine - thanks! I just commited it to
https://github.com/probml/probml-notebooks/blob/main/notebooks/logspace_jax.ipynb

**Comment by BitterKanegul** [comment]
Ahh I apologise for not doing it myself! Thank you so much!
