### ISSUE TITLE
 contextual bandit linear UCB

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#699]
Modify [our JAX Bayesian linear regression Thompson sampling agent](https://github.com/probml/bandits/blob/main/bandits/agents/linear_bandit.py) to support UCB. Then compare it to the LinUCB agent on the LinearNormal environment from [this tf agents colab](https://github.com/tensorflow/agents/blob/master/docs/tutorials/bandits_tutorial.ipynb)

**Comment by nileshnegi** [comment]
i'd like to take this up.

**Comment by posgnu** [comment]
@murphyk Hi, I would like to get reviews on my works on this.

* Here is the [code](https://gist.github.com/posgnu/cbbcfd9555661acb828e4d4f2df9f814#file-linear_bandit-py) for linear regression bandit now supporting UCB and epsilon greedy.
* [The results of comparison with LinUCB agent on the LinearNormal environment](https://colab.research.google.com/drive/1-7gpSsEa67E7x3pHABVYVmQv7z1Axqz0?usp=sharing)
* I also checked if the Thompson sampling exploration works normally by reproducing the experiment in your book. [colab](https://colab.research.google.com/drive/1A8vUKsSezoRGko0lkt_Q88Lb6BFJkLAf?usp=sharing)

May I know where is the proper location for a PR of this code?

**Comment by murphyk** [comment]
@posgnu I've merged your main bandit "library" code. Can you please refactor both notebooks  so they import your library code from pyprobml/scripts rather than duplicating the code in the notebook? Also, can you reorder the demos so you start by showing how to use your code, and then after that have a unit test that compares to prior implemenetations, using `assert np.allclose(your_vals, original_vals)`.  This way, someone who is not interested in the TF Agents code can ignore it :)

**Comment by posgnu** [comment]
@murphyk Since I was not sure where I should put the demo code and what each demo code is supposed to show, I only made a few changes that you mentioned in the comment.

* Both of the notebooks are now importing the `linear_bandit` module locally.
* Reorder the demo with TF-agent and add the unit test.

[tf-agent colab](https://colab.research.google.com/drive/1-7gpSsEa67E7x3pHABVYVmQv7z1Axqz0?usp=sharing)
[reproduce figure 36.7](https://colab.research.google.com/drive/1A8vUKsSezoRGko0lkt_Q88Lb6BFJkLAf?usp=sharing)

**Comment by murphyk** [comment]
I see you have `from linear_bandit import LinearBandit, ExplorationPolicy` but where is this code?
I think you need to do something like `wget pyprobml/scripts/linear_bandit.py`, right?
Please open PRs to add your two colabs to https://github.com/probml/probml-notebooks
