### ISSUE TITLE
Expected release date for 2nd edition of book

### ISSUE THREAD

**Issue by prl900** [probml/pyprobml#70]
Hi, this is not an issue but a question about the estimated release date for the new edition of the book. I'm really excited about this. Thank you very much for your work.

**Comment by murphyk** [comment]
It should be available December 2020.

**Comment by mjsML** [comment]
@murphyk Another question here, The chapters folder is gone ... is this intentional ?

**Comment by murphyk** [comment]
it's all still in flux.

**Comment by murphyk** [comment]
See http://mlbayes.ai for new book with updated code
