### ISSUE TITLE
convert matlab code for iterated posterior linearization smoother to JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#701]
The paper below generalizes the iterated extended/ unscented kalman smoother to use a more accurate posterior approximation.

Á. F. García-Fernández, L. Svensson, and S. Särkkä, “Iterated Posterior Linearization Smoother,” IEEE Trans. Automat. Contr., vol. 62, no. 4, pp. 2056–2063, Apr. 2017, doi: 10.1109/TAC.2016.2592681. [Online]. Available: https://web.archive.org/web/20200506190022id_/https://research.chalmers.se/publication/249335/file/249335_Fulltext.pdf

A matlab implementation for the 1d example in sec V of the paper can be found at
https://github.com/Agarciafernandez/IPLS.

The task is to translate this to JAX, and then to generalize / modularize it so it works with any transition model and observation model, including the multivariate case.

**Comment by chenxingqiang** [comment]
I working on this!
