### ISSUE TITLE
particle filter for Online Inference for Multiple Changepoint Problems in Jax

### ISSUE THREAD

**Issue by gerdm** [probml/pyprobml#705]
* Implement the sparse particle filter variant of BOCPD in Liu and Fearnhead (https://eprints.lancs.ac.uk/id/eprint/745/) since it is much more efficient for long sequences. Use this to reproduce their fig 1, that does online CPD for conjugate linear regression models

Followup to #680

**Comment by murphyk** [comment]
Solved in https://github.com/probml/pyprobml/blob/master/scripts/changepoint_detection.py

**Comment by murphyk** [comment]
This issue is the particle filtering extension of the existing changepoint code. Renaming.
