### ISSUE TITLE
translate ensembles with random priors demo from keras to JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#708]
Translate https://www.kaggle.com/code/gdmarmerola/introduction-to-randomized-prior-functions/notebook into JAX.

**Comment by peterchang0414** [comment]
I'd like to take this up!

**Comment by peterchang0414** [comment]
[My JAX/Flax implementation](https://colab.research.google.com/github/peterchang0414/randomized_priors/blob/main/randomized_priors.ipynb)

**Comment by NDOWAH** [comment]
I would like to work on this.
