### ISSUE TITLE
Figure 1.38 and 1.39 Octave error

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#71]
Error running dtreeDemoIris.m on GNU Octave, version 4.2.2
With NaN installed and having fisheriris.m in the same directory.
Colab runtime with no accelerator and normal memory config
Octave error :
```
error: load: unable to determine file format of 'fisheriris.m'
error: called from
    dtreeDemoIris at line 9 column 1
```

**Comment by murphyk** [comment]
pmtk3 is not being supported. Please rewrite the demo in python and add to
pyprobml.

**Comment by murphyk** [comment]
the problem is that 'fisheriris' is a dataset from stats toolbox.
I have cut and paste the data into dtreeIrisDemo.m but not yet plumbed it through.
In any case, this function demo is deprecated and has been replaced by
https://github.com/probml/pyprobml/blob/master/book1/trees/iris_dtree.ipynb
