### ISSUE TITLE
convert layer norm demo from torch to jax

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#718]
Translate this trivial demo to JAX
https://github.com/probml/probml-notebooks/blob/main/notebooks/layer_norm_torch.ipynb

**Comment by karm-patel** [comment]
Hi Dr. @murphyk, I would like to work on this.

**Comment by nalzok** [comment]
Ah I'm a few minutes late again: https://colab.research.google.com/drive/1ya3-nY35NoDsrLbGmchv_wsi0YuaPuIn?usp=sharing
