### ISSUE TITLE
Discrepancy between sensor_fusion_2d.py posterior mean and equation (4.125) in old textbook

### ISSUE THREAD

**Issue by JChunX** [probml/pyprobml#72]
Hi, I have been reading your textbook along with the new codes, and I think in `sensor_fusion_2d.py` there is a misplaced parenthesis on line 26 for the posterior mean calculation. According to (4.125), `post['sigma']` should be multiplied with the sum of `A.T.dot(sy_inv).dot(y.reshape(4,1) - py['mu'])` and `smu_inv.dot(pmu['mu']).reshape(2,1)`. The right parenthesis for `post['sigma'].dot()` should be moved to the end.

**Comment by murphyk** [comment]
thanks. Fixed!
(Someone else wrote this demo - I forget who. It's not very pythonic...)
