### ISSUE TITLE
reproduce 1d Laplace approx to BetaBinom posterior in JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#738]
@karm-patel 

Reproduce the Laplace example from https://github.com/probml/probml-notebooks/blob/main/notebooks/beta_binom_approx_post_pymc.ipynb but using optax and jax.hessian instead of PyMC.

**Comment by karm-patel** [comment]
Hi, Dr @murphyk 

I have tried to reproduce the Laplace approximation using Jax and compared it with pymc.

[**colab link**](https://drive.google.com/file/d/16RGxNAGMEqaMLjMRWYe9CldI16UIMCk8/view?usp=sharing)

| JAX | PYMC |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/59387624/164783436-385a3c34-2af1-414b-80d2-986f1452e47f.png)| ![image](https://user-images.githubusercontent.com/59387624/164781785-626250b6-56ea-42e2-a08b-8080340465b6.png) |

Can you please give your comments on this?

**Comment by murphyk** [comment]
Looks great! Please open a PR for this in probml-notebooks.
