### ISSUE TITLE
implement forwards-filter backward sampling for HMMs

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#742]

**Comment by peterchang0414** [comment]
I'd like to work on this!

**Comment by korntewin** [comment]
I have already create [MPR](https://github.com/probml/JSL/pull/36) based on this issue. Please review and feel free to suggest/discuss about the code ☺️.

**Comment by HussainAther** [comment]
I'm jumping in now, but I'd like to offer my help if possible.
