### ISSUE TITLE
translate remaining torch demos to JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#745]
- [x] [notebooks/layer_norm_torch](https://github.com/probml/probml-notebooks/blob/main/notebooks/layer_norm_torch.ipynb) - https://github.com/probml/probml-notebooks/pull/56, https://github.com/probml/probml-notebooks/pull/89
- [x] notebooks/text_preproc_torch - https://github.com/probml/probml-notebooks/pull/90
- [x] scripts/transposed_conv_torch
- [x] scripts/emnist_viz_pytorch

**Comment by nalzok** [comment]
Note that `notebooks/layer_norm_torch` has already been translated in https://github.com/probml/probml-notebooks/pull/56

**Comment by patel-zeel** [comment]
@nalzok I could not find `layer_norm_jax.ipynb` in `notebooks` folder, is it moved to another location?

**Comment by nalzok** [comment]
Looks like it was accidentally removed in an unrelated PR: https://github.com/probml/probml-notebooks/pull/58. I will make a new PR now.

**Comment by nalzok** [comment]
Hi @patel-zeel, it's done!

**Comment by yuanx749** [comment]
Hi @patel-zeel , I converted `scripts/transposed_conv_torch` to jax.
