### ISSUE TITLE
Individual chapters link gives 404

### ISSUE THREAD

**Issue by usingamgad** [probml/pyprobml#75]
The link for individual chapters in the README gives 404, cod you please fix the link?

**Comment by mjsML** [comment]
@usingamgad the second edition book is currently being written, the book chapters will be available once they are finalized (the latest timeline update puts that towards fall 2021 as per the [README.md](https://github.com/probml/pyprobml/blob/master/README.md)). The timeline is in flux as @murphyk schedule is overloaded. He should be able to provide us with an updated timeline soon.

**Comment by murphyk** [comment]
Exactly. I am working on the text for the second edition, I will release a
draft sometime in Spring 2021.
The code will be updated later (eg by Summer 2021).

**Comment by murphyk** [comment]
See http://mlbayes.ai for new book with updated code
