### ISSUE TITLE
apply GTSAM to LGSSM and compare to JSL code

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#754]
The [GTSAM library](https://github.com/borglab/gtsam) is a C++ library with Python wrappers for performing MAP estimaiton and (marginal) posterior inference in  Gaussian graphical models.  If the model is linear, the inference is exact; if it is nonlinear, it is approximate. The methods generalizes Kalman smoothing to arbitrary graphs.

The goal of this exercise is to reproduce the results of [JSL kalman smoother](https://github.com/probml/JSL/blob/main/jsl/lds/kalman_filter.py) and [Kalman sampler](https://github.com/probml/JSL/blob/main/jsl/demos/lds_sampling_demo.py) using GTSAM applied to some toy problem.

**Comment by dellaert** [comment]
Hey, here is code for Kalman smoothers:

- https://gtbook.github.io/gtsam-examples/KalmanSmootherExample.html
- https://gtbook.github.io/gtsam-examples/KalmanSmootherExample2.html

And here is a cool pic from the second one:

![image](https://user-images.githubusercontent.com/10515273/165607009-81c30c10-5731-4592-915d-0dcee3a1adef.png)
