### ISSUE TITLE
Written error in book 1 part 2.2.1

### ISSUE THREAD

**Issue by Andrewxu313** [probml/pyprobml#77]
![image](https://user-images.githubusercontent.com/34982739/103498334-57748800-4e7f-11eb-8b1f-c5a75bfab816.png)
Hi, Thanks for providing this excellent book. I just start reading it today.
I believe the sentense underlined in the picture should be "The false positive rate is defined as one minues the specifivity".

**Comment by murphyk** [comment]
fixed
