### ISSUE TITLE
Update notebooks as per the updated instructions

### ISSUE THREAD

**Issue by patel-zeel** [probml/pyprobml#770]
[The instructions](https://github.com/probml/pyprobml/blob/master/notebooks/README.md) have gone through major changes since the last modification of several notebooks. Mainly the following notebooks are affected:
- [x] Chpater 2 notebooks
- [x] [simpsons_paradox.ipynb](https://github.com/probml/pyprobml/blob/master/notebooks/book1/03/simpsons_paradox.ipynb)
- [x] book2 notebooks

Please update these notebooks.

**Comment by karm-patel** [comment]
I will do this.
