### ISSUE TITLE
Fix dead links for figure notebooks

### ISSUE THREAD

**Issue by patel-zeel** [probml/pyprobml#776]
As per the automatic redirection, several links expect a notebook but they are missing.

@karm-patel Please paste the list in this thread.

**Comment by karm-patel** [comment]
Following notebooks are not present in `pyprobml/book1` directory,
| Fig | Notebook | current location |
| -- |  -- |  -- |
| 1.12 |  emnist_viz_jax.ipynb | probml-notebooks/notebooks |
| 3.13 |  mix_ber_em_mnist.ipynb | Not exist (Renamed to mix_bernoulli_em_mnist.ipynb) |
| 4.17 |  gaussInferParamsMean2d.ipynb | Not exist (Renamed to gauss_infer_2d.ipynb)  |
| 9.5 |  fisher_vowel_demo.ipynb | Not exist (Renamed to fisher_discrim_vowel) |
| 9.6, 9.7 |  naive_bayes_mnist_jax.ipynb | probml-notebooks/notebooks-d2l |
| 15.25 |  positional_encoding_jax | probml-notebooks/notebooks-d2l |
| 19.14 | hbayes_maml.ipynb | probml-notebooks/notebooks |
|20.24, 20.25, 20.26 | ae_mnist_conv.ipynb | probml-notebooks/notebooks |

**Comment by karm-patel** [comment]
@patel-zeel 
Make corresponding changes to book source code
- [ ] 3.13: Rename to mix_bernoulli_em_mnist.ipynb
- [ ] 4.17: Rename to gauss_infer_2d.ipynb
- [ ] 9.5: Rename to fisher_discrim_vowe.ipynb
