### ISSUE TITLE
Create dummy notebooks for multi-notebook figures

### ISSUE THREAD

**Issue by patel-zeel** [probml/pyprobml#777]
Several figures are generated by multiple notebooks in the book1. Thus, we are going to create a dummy notebook for these figures which redirects to multiple notebooks.

@karm-patel Please add a task list to track the progress on this.

**Comment by karm-patel** [comment]
The following figures are created from multiple notebooks.
- [ ] 1.12: mnist_viz_tf.ipynb, emnist_viz_jax.ipynb, 
- [ ] 1.13: fashion_viz_tf.ipynb, cifar_viz_tf.ipynb, 
- [ ] 2.2: gauss_plot.ipynb, quantile_plot.ipynb, 
- [ ] 2.17: beta_dist_plot.ipynb, gamma_dist_plot.ipynb, 
- [ ] 4.14: dirichlet_3d_triangle_plot.ipynb, dirichlet_3d_spiky_plot.ipynb, 
- [ ] 4.20: logreg_iris_1d.ipynb, logreg_iris_bayes_1d_pymc3.ipynb, 
- [ ] 5.2: roc_plot.ipynb, pr_plot.ipynb, 
- [ ] 5.10: neymanPearson2.ipynb, twoPowerCurves.ipynb, 
- [ ] 8.1: extrema_fig_1d.ipynb, saddle.ipynb, 
- [ ] 8.14: newtonsMethodMinQuad.ipynb, newtonsMethodNonConvex.ipynb, 
- [ ] 8.26: mix_gauss_singularity.ipynb, mix_gauss_mle_vs_map.ipynb, 
- [ ] 11.10: ridgePathProstate.ipynb, lassoPathProstate.ipynb, 
- [ ] 11.19: linregRobustDemoCombined.ipynb, huberLossPlot.ipynb, 
- [ ] 18.4: bagging_trees.ipynb, rf_demo_2d.ipynb, 
- [ ] 20.24: vae_mnist_conv_lightning.ipynb, ae_mnist_conv.ipynb, 
- [ ] 20.25: vae_mnist_conv_lightning.ipynb, ae_mnist_conv.ipynb, 
- [ ] 20.26: vae_mnist_conv_lightning.ipynb, ae_mnist_conv.ipynb, 
- [ ] 20.30: manifold_swiss_sklearn.ipynb, manifold_digits_sklearn.ipynb, 
- [ ] 20.31: manifold_swiss_sklearn.ipynb, manifold_digits_sklearn.ipynb, 
- [ ] 20.33: manifold_swiss_sklearn.ipynb, manifold_digits_sklearn.ipynb, 
- [ ] 20.36: manifold_swiss_sklearn.ipynb, manifold_digits_sklearn.ipynb, 
- [ ] 20.37: manifold_swiss_sklearn.ipynb, manifold_digits_sklearn.ipynb, 
- [ ] 20.38: manifold_swiss_sklearn.ipynb, manifold_digits_sklearn.ipynb, 
- [ ] 20.41: manifold_swiss_sklearn.ipynb, manifold_digits_sklearn.ipynb, 
- [ ] 21.11: kmeans_silhouette.ipynb, gmm_2d.ipynb, kmeans_silhouette.ipynb,
