### ISSUE TITLE
Transfer helper .py files to probml-utils

### ISSUE THREAD

**Issue by karm-patel** [probml/pyprobml#793]
- Some .py files are in scripts/ which are directly imported in notebooks (for e.g `foo.py` imported as `import foo`) 
- Some .py files are stored in some different directories that are downloaded as `!wget foo.py`

These helper .py files need to be moved to probml_utils.

**Transferred files:**

| Old path (in pyprobml) |  New path (in probml-utils) |
| -- | -- | 
| pyprobm/scripts//mnist_helper_tf.py | probml_utils/mnist_helper_tf.py |
| pyprobml/vae/standalone/lvm_plots_utils.py | probml_utils/lvm_plots_utils.py |
| pyprobml/vae/standalone/vae_conv_mnist.py | probml_utils/vae_conv_mnist.py |
| pyprobml/scripts/mix_bernoulli_lib.py |  probml_utils/mix_bernoulli_lib.py |
| pyprobml/scripts/mix_bernoulli_em_mnist.py | probml_utils/mix_bernoulli_em_mnist.py |
| pyprobml/scripts/download_celeba.py | probml_utils/download_celeba.py |
| pyprobml/vae/standalone/vae_celeba_lightning.py |  probml_utils//vae_celeba_lightning.py |
| pyprobml/scripts/mfa_celeba_helpers.py |  probml_utils/mfa_celeba_helpers.py |

**Comment by murphyk** [comment]
this task is finished, closing
