### ISSUE TITLE
Should there be support for Python 2.7?

### ISSUE THREAD

**Issue by thvasilo** [probml/pyprobml#8]
So as I'm working on porting code over, I was wondering if compatibility with Python 2.7 is still required.

Most if not all of the packages used in the code (numpy, scipy, etc) already support Python 3, and adding support for 2.7 will just create some additional work where I have to have all the packages installed for both versions and always test for both before making changes.

I would recommend to just move to Python 3 for the whole code-base, but I wanted @murphyk 's input on this.

**Comment by murphyk** [comment]
sure, let's make the switch to python 3!

**Comment by thvasilo** [comment]
Great, I'll prepare a PR for the move the Python 3 then!
