### ISSUE TITLE
make SNGP demo in JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#819]
Convert [this TF demo of spectrally normalized neural GPs](https://www.tensorflow.org/tutorials/understanding/sngp) to JAX.
Use these JAX functions from edward2: [random_feature.py](https://github.com/google/edward2/blob/main/edward2/jax/nn/random_feature.py) and [normalization.py](https://github.com/google/edward2/blob/main/edward2/jax/nn/normalization.py) .

**Comment by nsanghi** [comment]
I am taking this up @murphyk
