### ISSUE TITLE
Section 2.3.2 R+ should be R non-negative

### ISSUE THREAD

**Issue by dwsmith1983** [probml/pyprobml#84]
In section 2.3.2, you say:

sj ∈ [0,∞] are the lengths of the two sides. Hence the hypothesis space is H = R2 × R2+, where R+ is the set of positive reals.

0 is not a positive number and since the domain is inclusive of 0, we should say R nonnegative R_{\geq 0} or however you would like to note it.

The draft date is 18 Jan 2021; I just started reading it yesterday so I think this is the most up to date version.

**Comment by murphyk** [comment]
Fixed.
