### ISSUE TITLE
Potential grammar issue

### ISSUE THREAD

**Issue by dwsmith1983** [probml/pyprobml#85]
This sentence, in section 2.4.4, sounds a bit off. Might just be me but take a look.

The advantage of the Bayesian approach is that by capturing uncertainty in the parameters θ, we will more accurately model uncertainty in our forecasts p(y|x, D) than we would using a plug-in approximation p(y|x, θˆ).

The fragment in question is:

"...than we would [be?] using a plug-in approximation..."

**Comment by murphyk** [comment]
fixed
