### ISSUE TITLE
remove duplicated notebooks

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#855]
Many notebooks in https://github.com/probml/pyprobml/tree/master/notebooks/misc have been copied to notebooks/book1 or notebooks/book2, sometimes with a changed name (eg https://github.com/probml/pyprobml/blob/master/notebooks/misc/bnn_mnist_sgld_whitejax.ipynb -> https://github.com/probml/pyprobml/blob/master/notebooks/book2/18/bnn_mnist_sgld.ipynb). 
Please move all such duplicates out of notebooks/misc and put in https://github.com/probml/pyprobml/tree/master/deprecated.

The final result should be that notebooks/misc just contains "orphans", ie notebooks that are not referred to anywhere in either book. It will be easier to identify a home for these orphans once there are fewer of them :)

**Comment by karm-patel** [comment]
Dr. @murphyk, I have moved 49 notebooks having the same names. Still, there are 130 notebooks left in `notebooks/misc`.
I'm still figuring out the way to find out duplicate notebooks which do not have the same names.
