### ISSUE TITLE
Missing data directory

### ISSUE THREAD

**Issue by thvasilo** [probml/pyprobml#9]
Some of the examples include a call to `utils/util.load_mat` that depends on a `DATA_DIR` being available where the .mat files are supposed to be.

Here's what `grep -r -i --include \*.py load_mat` gives me when run in examples.
```
prostateComparisonOrig.py:#X = util.load_mat('prostate')
naiveBayesBowDemo.py:data = util.load_mat('XwindowsDocData')
logregSATdemo.py:data = util.load_mat('sat/sat.mat')
gaussHeightWeight.py:data = util.load_mat('heightWeight')
newsgroupsVisualize.py:data = util.load_mat('20news_w100')
shuffledDigitsDemo.py:data = util.load_mat('mnistAll')
utils/util.py:# def load_mat(matName):
surfaceFitDemo.py:data = util.load_mat('moteData/moteData.mat')
kmeansHeightWeight.py:data = util.load_mat('heightWeight')
```

How would @murphyk recommend this is handled? Should the data directory be replicated in this repo so that the datasets become available for the scripts?

**Comment by murphyk** [comment]
Yes, I would recommend duplicating the data into a new directory, so that
pyprobml is self contained.

**Comment by murphyk** [comment]
I have taken care of this (I copied over the data from the matlab repo to
the python repo).

**Comment by thvasilo** [comment]
Great, I've tested it on the above files and it seems to work now. 

Just needed a small change in util.load_mat, since we are running examples from the repo root, `../data` will point above that, so `load_mat` needs to have `./data` as the default argument instead. I'll include this change in the Python 3 PR.
