### ISSUE TITLE
Should 0\leq f_c(x; \theta)\leq 1 be the norm of the function?

### ISSUE THREAD

**Issue by dwsmith1983** [probml/pyprobml#90]
In chapter 3, on page 50, under equation 3.27, it says we require

0\leq f_c(x; \theta)\leq 1

I am a little rusty, I have to admit, but should that be the norm of the function? Feel free to reject this if this is wrong.

**Comment by murphyk** [comment]
No, f_c(x) returns a scalar for each class c, so f_{1:C}(x) is the vector of probabilities. 
If this is passed directly to multinomial, we require the output of the function to satisfy 0 <= f_c(x) <=1 for each output c.
