### ISSUE TITLE
Add Grid approximation

### ISSUE THREAD

**Issue by karm-patel** [probml/pyprobml#920]
Add Grid approximation in https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/book1/04/laplace_approx_beta_binom_jax.ipynb#scrollTo=f9c1338c.

So we can complete Fig 7.2 by laexification.
![image](https://user-images.githubusercontent.com/59387624/174624080-89665741-cedd-4d4f-8e3a-6697dbceb617.png)

**Note: Also we need to separate PYMC & Blackjack notebook.**

**Comment by murphyk** [comment]
Note : that notebook uses ` import pymc3 as pm` which will also need updating

**Comment by karm-patel** [comment]
This is resolved in #968
