### ISSUE TITLE
VMG code should be moved to probml-utils

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#930]
Currently https://github.com/probml/pyprobml/blob/master/notebooks/book2/09/variational_mixture_gaussians_demo.ipynb (fig 9.7)
does not work. It seems to depend on  the following deprecated script: https://github.com/probml/pyprobml/blob/master/deprecated/scripts/variational_mixture_gaussians.py. The latter should be added to probml-utils.

**Comment by karm-patel** [comment]
Done
