### ISSUE TITLE
change all filenames to snake case

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#931]
There are several files (eg https://github.com/probml/pyprobml/blob/master/notebooks/book2/17/gprDemoChangeHparams.ipynb) that use CamelCase, but according to https://softwareengineering.stackexchange.com/questions/308972/python-file-naming-convention, pep8 says filenames should be lowercase with underscores, eg `gp_regression_change_hparams.ipynb`). We should change the filenames now before they become "enshrined" in the book for ever.

**Comment by nipunbatra** [comment]
Perhaps the following links should be sufficient to rename all such files:

Using Python: https://www.geeksforgeeks.org/python-program-to-convert-camel-case-string-to-snake-case/

Using sed: https://askubuntu.com/a/844752/176475
