### ISSUE TITLE
convert legacy matlab code to python

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#99]
If you want to contribute a Python version of a figure, follow these steps:

- Check the list of open issues for ones with a name like "Convert foo to Python". Such issues have the tag 'Figures'.
Each issue has a link to the Matlab file that was used to generate the  figure, and a figure number.
Figure numbers refer to this version of the book: https://github.com/probml/pml-book/releases/tag/2021-03-08. 
Consult the pdf file to see what the figure should look like.
  
- Follow [these guidelines](https://github.com/probml/pyprobml/blob/master/CONTRIBUTING.md) for how to contribute code.

- Test your code works in Google colab, and make a pull request. Please include the generated image(s) in your PR, and add a tag which mentions the issue you are solving.

- [Here](https://github.com/probml/pyprobml/pulls?q=is%3Apr+author%3Agerdm) is an example of good PR.

- If you are a student and want to be considered for the **Google Summer of Code**, please apply [here](https://summerofcode.withgoogle.com/get-started/) after **March 29th**. You should have at least 2 PRs succesfully added to this repo before applying. Please follow the style guidelines mentioned above.

**Comment by ryzbaka** [comment]
Hi @murphyk , I'm interested in converting these examples to python with JAX. 

Is there anything I should know before getting started?

**Comment by Garvit9000c** [comment]
Hi @murphyk Sir, I am Highly Enthusiastic , in converting These example to python with JAX.
And i am Already Building a Project with JAX , will upload the repo soon!
 What should be my First Step in Getting started!

**Comment by murphyk** [comment]
I will provide more details on how to contribute soon.

**Comment by Garvit9000c** [comment]
Ok Sir, That's crystal clear now!🙌

**Comment by animesh-007** [comment]
@murphyk I would like to contribute to the project of converting Tensorflow DL examples to JAX / Flax / Haiku.
Could you guide me on this?

**Comment by ryzbaka** [comment]
I downloaded the version of the book from the link [here](https://github.com/probml/pml-book/releases/tag/2021-03-08) as mentioned in the issue description.
Figure number 3.13 in the mcodes.txt file is a demo of Gaussian imputation, whereas in the book figure 3.13 is a visualization of the first 25 digits of MNIST.

![image](https://user-images.githubusercontent.com/26931277/110791147-e0e97180-8297-11eb-8989-4db08b3da9a4.png)

It'd be great if someone could help me out with this issue.

**Comment by mjsML** [comment]
@ryzbaka the issue has been updated, please check the new codes... the version you are referring to might be stale.

**Comment by mjsML** [comment]
I have created an issue for each figure so this becomes more streamlined.

**Comment by call-me-bk** [comment]
https://github.com/victorlei/smop Does this help? I can try and work on this if nobody else is working on it right now!

**Comment by animesh-007** [comment]
@mjsML Could you pin this issue so that it is easily accessible to everyone?

**Comment by mjsML** [comment]
> https://github.com/victorlei/smop Does this help? I can try and take a look at this if not a lot of poeple are working on this right now!

not sure ... give it a try with a single graph and see if it works as expected.

**Comment by radhathakare** [comment]
Hi myself Radha  , I would like to convert tensorflow examples to JAX. I have done 2 projects in  ML with tensorflow and NLP and working with python.

**Comment by radhathakare** [comment]
Can anyone guide me for tensorflow to JAX project ?

**Comment by animesh-007** [comment]
> Can anyone guide me for tensorflow to JAX project ?

Hi @radhathakare. You can go through the following discussion for the update.
[Discussion ](https://github.com/probml/pyprobml/issues/100#issuecomment-797804463)

**Comment by mjsML** [comment]
@animesh-007 @ashishpapanai @shivaditya-meduri @Abdelrahman350 @call-me-bk @ryzbaka @always-newbie161 @nappaillav @alen1010 

All,

Thank you so much for your efforts and activity, We really appreciate all the hard work put into your contributions.

Given that both @murphyk and myself have full time jobs, please do accept our apologies for the delayed feedback.

I would kindly ask you to please do ensure the following to make sure our feedback is as effective as possible:

1. Please make sure your PR has only one commit (your draft ones can go on your own local machine).
2. Before even committing at all please make sure your commit : 
-. Is tested and working (**specially in Google's Colab**). A commit by definition is a working atomic unit of code to your best effort. not a "ctrl/cmd +s" replacement. We are working on an automated tested pipeline with the help of a bot, we have few bugs to squash and this will be a requirement moving forward.
-. Produces the figure properly that shows in the book (unless it's a minor difference like @murphyk mentioned above).
-. Is a single file per change (no extra generated files or datasets), if your code requires extra files, please ask in the issue of the related figure issue first.
5. Please try to put forward your best work, no magic values (unless you explicitly ask in the issue and get the Ok to use it).
Please note that audience of this repo are people who are of various backgrounds, some might not be on the same python level as you are, so we ask kindly to make sure your code is as [pythonic as possible ](https://google.github.io/styleguide/pyguide.html).
6. Draft PRs are not scratch pads, draft PRs are supposed to be used for a change that will need to go for release [planning for example](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests). A commit is supposed to be tested, working unit of code, while it does say on the github guidelines that a draft means it's not ready for review, it doesn't mention that commits supposedly are supposed to be working units of code (in fact some organizations auto block commits that don't follow style guides and or breaks the build, some even force developers to put a dollar in the 'broke the build' jar if their commit breaks the build 😄 ) . 
7. To avoid duplication, please check the pull requests and issues to see if someone has already pushed a pull request.
8. If your PR is ready to go, please make sure you mention the issue it fixes, and request a review from both @murphyk and myself.

And finally to save everyone's time, I would ask all the open pull request owners to review their work if they feel it needs more work in any of the areas I mentioned, please close it and open when ready for review. if your PR has lots of reviews already please try to get it to a review shape asap and do your best to follow the guidelines I mentioned above for your future PRs.

Thank you and looking forward to your contribution.

M

**Comment by murphyk** [comment]
Important update on the Google Summer of Code. You should apply at [this page](https://summerofcode.withgoogle.com/get-started/) starting **March 29th**. (Deadline is April 13th). A committee will then rank candidates and select 1 or 2. Candidates will be judged by the quality of their contributions to the pyprobml repo. Please follow the style guidelines that Mahmoud listed above.  (We will publish official contributors guide soon - stay tuned.)

**Comment by Drishttii** [comment]
Hi, I am Drishti, an outreachy applicant. I am interested in contributing by writing examples for JAX. Is there a public channel or chat where I can get more information about the project?

**Comment by animesh-007** [comment]
> Hi, I am Drishti, an outreachy applicant. I am interested in contributing by writing examples for JAX. Is there a public channel or chat where I can get more information about the project?

Hi @Drishttii. We don't have any public channels for the project right now, which is also mentioned by one of the mentors.
[Link to the message](https://github.com/probml/pyprobml/issues/228#issuecomment-798873538)

**Comment by murphyk** [comment]
@Drishttii  We do not have bandwidth to support any public chat channels - all communication is via the specific issues in this repo. (Note: for the summer, we will add more issues, related to figures from vol 2 of the book. This may involve more jax and/or pytorch coding, using libraries like pyro. But the details are not yet decided.)

**Comment by Drishttii** [comment]
Alright. Thank you :)

**Comment by aadi-mishra** [comment]
Hi , I am interested in contributing to the project. I would appreciate if you can guide me on How to get involved ?

**Comment by nouranali** [comment]
Hi I'm interested in the TensorFlow to JAX project but I don't know where should I contribute, can someone guide me?

**Comment by Abdelrahman350** [comment]
Hello, I shared my draft proposal, please review it.

@murphyk @mjsML

**Comment by mjsML** [comment]
All,

As @murphyk mentioned, Please apply on the GSOC website and we will try to give you feedback on your draft if time permits.

As for the second project (TF or others to JAX) it's not as straightforward. IIUC (my) expectation is that one would read the book, look at the [supplement notebooks](https://github.com/probml/pyprobml/tree/master/notebooks), [JAX examples](https://github.com/google/jax/tree/master/examples), [Flax examples](https://github.com/google/flax/tree/master/examples), [NumPyro examples](http://num.pyro.ai/en/latest/index.html#introductory-tutorials), [PyMC3 examples](https://docs.pymc.io/notebooks/GLM-hierarchical-jax.html) or any other computational framework or language (e.g MatLab toolboxes) on the web and create your own notebook that expands or applies concepts in the book in an illustrative manner (i.e. here is how you do foo task in JAX where foo is a topic touched by or is an expansion on a topic in the book). 

Also, this scope also is not written in stone, given how recent JAX is, it has its own [rough edges](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html) and this is the nature of the beast. Trying to create an example for bleeding-edge tech, you might end up spending your summer opening issues for the JAX team on their repo or you might end up writing an example that gets cited by a paper 🙂 

@murphyk please feel free to expand on/ correct this.

I hope this was helpful.
M
